import { describe, it, expect } from "vitest";
import { createInitialState, applyCommand } from "@/lib/simulation/simulationEngine";
import { migrateEnergy, emptyEnergySite, processEnergyUntil, pvPowerKw, electricWorkSteps, processElectricPhase, installEnergyUpgrade } from "@/lib/simulation/energyEngine";
import { ELECTRIC_MODELS, electricFields, ENERGY_RULES as R } from "@/lib/simulation/electricCatalog";
import { VEHICLE_CATALOG, CITIES } from "@/lib/simulation/gameRules";
import { buildDeployment, buildTourPlan, processTours } from "@/lib/simulation/tourEngine";
import { buildEmptyWorkSteps, buildPhases } from "@/lib/simulation/driverTimeEngine";
import { compactHistory, readArchiveRecords } from "@/lib/historyArchive";
function base() { const s:any=createInitialState({companyName:"Energie-Test",playerName:"Test",partnerName:"Mara"}).state; s.company.accountCents=1000000000; s.openCosts=[]; return s; }
function truck(id="ev",city="Hamburg",model="electric_standard") {return {id,branchId:"b",status:"free",condition:100,locationCity:city,bodyType:"planen",capacityTons:12,...electricFields(VEHICLE_CATALOG[model])};}
function isolated() {const s=base();s.gameTime=0;s.branches=[{id:"b",name:"Solarhof",city:"Hamburg",status:"active"}];s.vehicles=[truck()];s.vehicles[0].batteryKWh=0;migrateEnergy(s);s.energy.sites.b=emptyEnergySite();return s;}
function close(a,b){expect(a).toBeCloseTo(b,6);}
describe("Depot energy conservation and persistence",()=>{
 it("migrates old games without free assets or retroactive PV",()=>{const s=base();const old=structuredClone(s.vehicles);migrateEnergy(s);const e=structuredClone(s.energy);migrateEnergy(s);expect(s.energy).toEqual(e);expect(s.energy.sites).toEqual({});expect(s.vehicles).toEqual(old);expect(e.lastMin).toBe(s.gameTime);});
 it("uses power limits, excludes vehicles away or on a trip, and charges exactly once",()=>{const s=isolated(),site=s.energy.sites.b;site.dcChargers=2;site.gridKw=50;s.vehicles.push({...truck("away","Berlin"),batteryKWh:0},{...truck("trip"),status:"on_trip",batteryKWh:0});processEnergyUntil(s,60);close(s.vehicles[0].batteryKWh,46);close(site.totals.gridKWh,50);close(site.totals.chargeLossKWh,4);expect(s.vehicles[1].batteryKWh).toBe(0);expect(s.vehicles[2].batteryKWh).toBe(0);const prev=structuredClone(s.energy);processEnergyUntil(s,60);expect(s.energy).toEqual(prev);});
 it("reassigns a freed port within the hour without overcharging",()=>{const s=isolated(),site=s.energy.sites.b;site.wallboxes=1;s.vehicles[0].batteryKWh=319;s.vehicles.push({...truck("z"),batteryKWh:0});processEnergyUntil(s,60);close(s.vehicles[0].batteryKWh,320);close(s.vehicles[1].batteryKWh,22*.92-1);close(site.totals.gridKWh,22);});
 it("has no PV at night; accounts for all PV, storage and charger losses",()=>{const s=isolated(),site=s.energy.sites.b;site.pvKwp=250;site.storageKWh=100;site.storageKw=50;site.wallboxes=2;site.dcChargers=1;expect(pvPowerKw(s.branches[0],site,0)).toBe(0);expect(pvPowerKw(s.branches[0],site,720)).toBeGreaterThan(0);processEnergyUntil(s,1440);const t=site.totals;close(t.pvKWh,t.pvDirectKWh+t.pvStoredKWh+t.exportKWh);close(t.pvStoredKWh,site.storedKWh+t.storageOutKWh+t.storageLossKWh);close(t.pvDirectKWh+t.storageOutKWh+t.gridKWh,t.truckKWh+t.chargeLossKWh);expect(s.vehicles[0].batteryKWh).toBeLessThanOrEqual(320);});
 it("discharges only stored solar power, with loss and grid fallback",()=>{const s=isolated(),site=s.energy.sites.b;site.storageKWh=100;site.storageKw=50;site.storedKWh=10;site.dcChargers=1;processEnergyUntil(s,60);close(site.totals.storageOutKWh,9.5);close(site.storedKWh,0);close(site.totals.gridKWh,50);close(s.vehicles[0].batteryKWh,59.5*.92);});
 it("is invariant across 1 day / hourly / 15-minute integration and JSON reload",()=>{const setup=()=>{const s=isolated();Object.assign(s.energy.sites.b,{pvKwp:250,storageKWh:200,storageKw:100,dcChargers:2});s.vehicles=Array.from({length:5},(_,i)=>({...truck("ev"+i),batteryKWh:i*2}));return s;};const a=setup(),b=setup(),c=setup();processEnergyUntil(a,1440);for(let m=60;m<=1440;m+=60)processEnergyUntil(b,m);for(let m=15;m<=1440;m+=15)processEnergyUntil(c,m);for(const other of [b,c]){for(const k of Object.keys(a.energy.sites.b.totals))close(a.energy.sites.b.totals[k],other.energy.sites.b.totals[k]);a.vehicles.forEach((v,i)=>close(v.batteryKWh,other.vehicles[i].batteryKWh));expect(other.energy.sites.b.billedGridCents).toBe(a.energy.sites.b.billedGridCents);}const reload=JSON.parse(JSON.stringify(a));processEnergyUntil(a,1500);processEnergyUntil(reload,1500);expect(reload.energy).toEqual(a.energy);});
 it("preserves older daily rows in the lossless archive",async()=>{const s=isolated();s.energy.sites.b.pvKwp=50;processEnergyUntil(s,92*1440);const site=s.energy.sites.b;expect(site.daily).toHaveLength(90);const archived=s.historyOutbox.filter(x=>x.kind==="energyDays");expect(archived).toHaveLength(2);close(site.totals.pvKWh,[...site.daily,...archived.map(x=>x.data)].reduce((n,r)=>n+r.pvKWh,0));const compact=await compactHistory(s);const rows=[];for(const c of compact.historyArchive.chunks)rows.push(...await readArchiveRecords(c,c.data));expect(rows.filter(r=>r.kind==="energyDays")).toHaveLength(2);});
 it("books investment and accrual settlements, rejects unaffordable builds",()=>{const s=isolated();const before=s.company.accountCents;installEnergyUpgrade(s,{branchId:"b",upgrade:"pv"});expect(s.company.accountCents).toBe(before-3500000);expect(s.accounting.assets.some(a=>a.account==="1220"&&a.acquisitionCostCents===3500000)).toBe(true);expect(s.energy.sites.b.pvKwp).toBe(50);s.company.accountCents=0;expect(()=>installEnergyUpgrade(s,{branchId:"b",upgrade:"storage"})).toThrow();expect(s.energy.sites.b.storageKWh).toBe(0);});
});
describe("Electric route planning and real phases",()=>{
 it.each(Object.keys(ELECTRIC_MODELS))("plans a feasible long route for %s without mutating the vehicle",model=>{const s=isolated(),v=truck("ev","Hamburg",model),old=structuredClone(v);v.batteryKWh=old.batteryKWh*.5;const before=structuredClone(v);const p=electricWorkSteps(s,v,buildEmptyWorkSteps("Hamburg","München"));expect(p.error).toBeUndefined();expect(p.energy.stops.length).toBeGreaterThan(0);expect(v).toEqual(before);expect(p.energy.finalBatteryKWh).toBeGreaterThanOrEqual(v.batteryCapacityKWh*.1-1e-7);close(p.energy.startBatteryKWh+p.energy.publicChargeKWh-p.energy.usedKWh,p.energy.finalBatteryKWh);expect(p.energy.publicCostCents).toBeGreaterThan(0);});
 it("rejects an unreachable route and preserves diesel work steps",()=>{const s=isolated();s.energy.closedPublicCities=CITIES;const v=truck();v.batteryKWh=32;expect(electricWorkSteps(s,v,buildEmptyWorkSteps("Hamburg","München")).error).toBeTruthy();const steps=buildEmptyWorkSteps("Hamburg","München");expect(electricWorkSteps(s,{powertrain:"diesel"},steps)).toEqual({steps,energy:null});});
 it("phase splitting conserves charge and drive energy and reserve",()=>{const s=isolated(),v=s.vehicles[0];v.batteryKWh=100;const p=electricWorkSteps(s,v,buildEmptyWorkSteps("Hamburg","München"));const plan=buildPhases(p.steps,{workMin:470,driveMin:250},0);const trip={vehicleId:v.id,branchId:"b"};expect(plan.phases.some(p=>p.type==="daily_rest")).toBe(true);for(const phase of plan.phases){processElectricPhase(s,trip,phase,phase.endMin);expect(v.batteryKWh).toBeGreaterThanOrEqual(32-1e-7);expect(v.batteryKWh).toBeLessThanOrEqual(320);}close(v.batteryKWh,p.energy.finalBatteryKWh);close(s.energy.sites.b.totals.driveKWh,p.energy.usedKWh);close(s.energy.sites.b.totals.publicBatteryKWh,p.energy.publicChargeKWh);});
 it("buys and leases actual electric vehicles with batteries",()=>{const s=base(),b=s.branches[0];s.vehicles=[];for(const id of Object.keys(ELECTRIC_MODELS)){applyCommand(s,"buyVehicle",{vehicleType:id,bodyType:"planen",branchId:b.id});}const bought=s.vehicles.slice();s.vehicles=[];for(const id of Object.keys(ELECTRIC_MODELS)){applyCommand(s,"leaseTruck",{offerId:id+"_flex",bodyType:"planen",branchId:b.id,provisionCity:b.city});}for(const v of [...bought,...s.vehicles]){expect(v.powertrain).toBe("electric");expect(v.batteryKWh).toBe(v.batteryCapacityKWh);expect(v.consumptionPer100km).toBe(0);}});
 it("integrates sub-hour commands immediately",()=>{const s=base();migrateEnergy(s);const b=s.branches[0];s.energy.sites[b.id]={...emptyEnergySite(),wallboxes:1};s.vehicles=[{...truck("ev",b.city),branchId:b.id,batteryKWh:0}];const start=s.gameTime;applyCommand(s,"advanceTime",{minutes:7});expect(s.gameTime).toBe(start+7);expect(s.energy.lastMin).toBe(start+7);close(s.vehicles[0].batteryKWh,22*.92*7/60);});
});
