import {describe,it,expect} from "vitest";
import {createInitialState,applyCommand} from "@/lib/simulation/simulationEngine";
import {computeTargetGameMinute} from "@/lib/simulation/timeControlEngine";
function initial(){const s=createInitialState({}).state;applyCommand(s,"advanceTime",{minutes:0});return s;}
describe("Livezeit und manueller Vorlauf",()=>{
 it("verarbeitet alle fünf Sekunden genau 15 Spielminuten",()=>{const s=initial(),start=s.gameTime;applyCommand(s,"enableAutomation",{serverNowMs:100000});expect(computeTargetGameMinute(s.timeControl,104999)).toBe(start);applyCommand(s,"syncAutomation",{serverNowMs:105000});expect(s.gameTime).toBe(start+15);applyCommand(s,"syncAutomation",{serverNowMs:109999});expect(s.gameTime).toBe(start+15);applyCommand(s,"syncAutomation",{serverNowMs:110000});expect(s.gameTime).toBe(start+30);});
 it.each([60,1440])("Live läuft nach +%s Minuten am neuen Stand weiter",minutes=>{const s=initial(),start=s.gameTime;applyCommand(s,"enableAutomation",{serverNowMs:100000});const result=applyCommand(s,"advanceTime",{minutes,silentPhoneAdvance:true,serverNowMs:101000}).result;expect(result.stopped).toBe(false);expect(result.advancedMinutes).toBe(minutes);expect(s.gameTime).toBe(start+minutes);applyCommand(s,"syncAutomation",{serverNowMs:106000});expect(s.gameTime).toBe(start+minutes+15);});
 it("alte Zeitanker verursachen weder Rücksprung noch acht Minuten Stillstand",()=>{const s=initial();applyCommand(s,"enableAutomation",{serverNowMs:100000});s.gameTime+=1440;const expected=s.gameTime;applyCommand(s,"syncAutomation",{serverNowMs:105000});expect(s.gameTime).toBe(expected);applyCommand(s,"syncAutomation",{serverNowMs:110000});expect(s.gameTime).toBe(expected+15);});
 it("pausierte Simulation verändert ihre Spielzeit nicht",()=>{const s=initial();applyCommand(s,"enableAutomation",{serverNowMs:100000});applyCommand(s,"syncAutomation",{serverNowMs:105000});applyCommand(s,"pauseAutomation",{serverNowMs:105000});const before=s.gameTime;applyCommand(s,"syncAutomation",{serverNowMs:150000});expect(s.gameTime).toBe(before);});
 it("ausstehende Freigabe meldet den konkreten Stopp und tatsächlichen Fortschritt",()=>{const s=initial();s.delegation.rules.approvalMode="stop";s.approvals.pending.push({id:"pending-test",status:"pending"});const r=applyCommand(s,"advanceTime",{minutes:1440,silentPhoneAdvance:true}).result;expect(r.stopReason).toBe("pending_approval");expect(r.advancedMinutes).toBe(0);expect(r.requestedMinutes).toBe(1440);});
});
