import {it,expect} from "vitest";
import {createInitialState,applyCommand} from "../src/lib/simulation/simulationEngine";
import {setManagementGoal,processManagementGoals,managementGoalProgress,managementPriority,cancelManagementGoal} from "../src/lib/simulation/managementGoals";
import {getStaffPhoneData} from "../src/lib/simulation/staffPhone";
import {generateBranchDecisions} from "../src/lib/simulation/branchManagerEngine";
function setup(){const s:any=createInitialState({}).state;applyCommand(s,"advanceTime",{minutes:0});s.employees.push({id:"m",name:"Maria",role:"branch_manager",employmentStatus:"employed",attendance:"present",assignedBranchId:s.branches[0].id,managementMode:"autonomous",autonomousDailyBudgetCents:0},{id:"a",name:"Alex",role:"assistant",employmentStatus:"employed",attendance:"present"});s.gameTime=540;return s;}
it("accepts a real phone goal once and preserves spending authority",()=>{const s=setup(),m=s.employees.find(x=>x.id==="m");const a=getStaffPhoneData(s,"m").actions.find(a=>a.id==="management_goal:reliability");const balance=s.company.accountCents;applyCommand(s,"staffPhoneCommand",{employeeId:"m",...a.params});expect(s.journey.mandates).toHaveLength(1);expect(()=>applyCommand(s,"staffPhoneCommand",{employeeId:"m",...a.params})).toThrow();expect(m.autonomousDailyBudgetCents).toBe(0);expect(s.company.accountCents).toBe(balance);});
it("isolates branch measurements and rejects misleading tiny samples",()=>{const s=setup();setManagementGoal(s,{employeeId:"m",kind:"reliability"});const g=s.journey.mandates[0];s.journey.totals.delivered=100;s.journey.totals.onTime=100;expect(managementGoalProgress(s,g).delivered).toBe(0);s.journey.branchTotals[g.branchId]={delivered:1,onTime:1};s.gameTime=g.dueMin;processManagementGoals(s,s.gameTime);expect(g.status).toBe("insufficient");expect(g.result.percent).toBe(100);});
it("reviews at the deadline and archives exactly once",()=>{const s=setup();setManagementGoal(s,{employeeId:"m",kind:"reliability"});const g=s.journey.mandates[0];s.journey.branchTotals[g.branchId]={delivered:10,onTime:9};s.gameTime=g.dueMin-1;processManagementGoals(s,s.gameTime);expect(g.status).toBe("active");s.gameTime++;processManagementGoals(s,s.gameTime);processManagementGoals(s,s.gameTime);expect(g.status).toBe("achieved");expect(s.historyOutbox.filter(x=>x.data.type==="management_goal")).toHaveLength(1);});
it("prioritizes staff shortages without approving expenditure",()=>{const s=setup();setManagementGoal(s,{employeeId:"m",kind:"staffing"});s.drivers=[];const m=s.employees.find(x=>x.id==="m");expect(managementPriority(s,m,s.branches[0])).toBe("hire_driver");const balance=s.company.accountCents;for(let day=1;day<8;day++){s.gameTime=day*1440+540;generateBranchDecisions(s);}expect(s.branchDecisions.some(d=>d.type==="hire_driver"&&d.status==="pending")).toBe(true);expect(s.company.accountCents).toBe(balance);expect(s.drivers).toHaveLength(0);});
it("respects withdrawn personnel responsibility despite staffing goals",()=>{const s=setup();setManagementGoal(s,{employeeId:"m",kind:"staffing"});s.drivers=[];s.employees.find(x=>x.id==="m").responsibilities={staff:false,growth:false,fleet:false,costs:false,orders:false};for(let day=1;day<8;day++){s.gameTime=day*1440+540;generateBranchDecisions(s);}expect(s.branchDecisions).toHaveLength(0);});
it("interrupts goals on reassignment and preserves cancelled reviews across saves",()=>{const s=setup();setManagementGoal(s,{employeeId:"m",kind:"staffing"});s.employees.find(x=>x.id==="m").assignedBranchId="elsewhere";processManagementGoals(s,s.gameTime);expect(s.journey.mandates[0].status).toBe("interrupted");setManagementGoal(s,{employeeId:"a",kind:"reliability"});cancelManagementGoal(s,{id:s.journey.mandates[1].id});expect(JSON.parse(JSON.stringify(s)).journey.mandates[1].status).toBe("cancelled");});
