import {it,expect} from "vitest";
import {createInitialState,applyCommand} from "../src/lib/simulation/simulationEngine";
import {migrateJourney,startJourneyPath,recordJourneyEvent,processJourney} from "../src/lib/simulation/playerJourney";
function setup(){const s:any=createInitialState({}).state;applyCommand(s,"advanceTime",{minutes:0});return s;}
it("migrates without retroactive progress and does not reset existing paths",()=>{const s=setup();expect(s.journey.totals.onTime).toBe(0);startJourneyPath(s,"reliable");const old=structuredClone(s.journey);migrateJourney(s);expect(s.journey).toEqual(old);});
it("scales goals, counts real events and grants each milestone once",()=>{const s=setup();startJourneyPath(s,"reliable");for(let i=0;i<5;i++)recordJourneyEvent(s,{type:"delivery_completed",gameTime:s.gameTime,driverId:s.drivers[0].id,vehicleId:s.vehicles[0].id,details:{onTime:true,toCity:"Hamburg"}});expect(s.journey.goals[0].completedAtMin).toBe(s.gameTime);expect(s.journey.badges).toBe(1);processJourney(s,s.gameTime);expect(s.journey.badges).toBe(1);expect(()=>startJourneyPath(s,"green")).toThrow();});
it("closes weeks before boundary events and bounds retained reviews",()=>{const s=setup();recordJourneyEvent(s,{type:"course_completed",gameTime:10080,details:{}});expect(s.journey.weeks[0].values.courses).toBe(0);processJourney(s,20160);expect(s.journey.weeks[1].values.courses).toBe(1);for(let i=3;i<20;i++)processJourney(s,i*10080);expect(s.journey.weeks).toHaveLength(8);expect(s.historyOutbox.some(x=>x.data.type==="journey_week")).toBe(true);});
it("preserves day/hour/quarter-hour results",()=>{const initial=setup();const states=[1440,60,15].map(step=>{const s=structuredClone(initial);for(let m=0;m<1440;m+=step)applyCommand(s,"advanceTime",{minutes:step,silentPhoneAdvance:true});return s.journey;});expect(states[1]).toEqual(states[0]);expect(states[2]).toEqual(states[0]);});

import {processCompanyStories,chooseCompanyStory} from "../src/lib/simulation/companyStories";
function storySetup(){const s=setup();startJourneyPath(s,"people");s.gameTime=s.journey.nextArcMin;const driver=s.drivers[0];driver.employmentStatus="employed";recordJourneyEvent(s,{type:"delivery_completed",gameTime:s.gameTime,driverId:driver.id,vehicleId:s.vehicles[0].id,details:{onTime:true,customer:"Nordhafen"}});processCompanyStories(s,s.gameTime);return s;}
it("starts from an actual employee success and waits for that person's actual course",()=>{const s=storySetup(),a=s.journey.arcs[0];expect(a.name).toBe(s.drivers[0].name);chooseCompanyStory(s,{id:a.id,stage:0,choice:"learning"});recordJourneyEvent(s,{type:"course_completed",gameTime:s.gameTime,personId:"someone_else"});expect(a.status).toBe("waiting");recordJourneyEvent(s,{type:"course_completed",gameTime:s.gameTime,personId:a.driverId});expect(a.stage).toBe(2);chooseCompanyStory(s,{id:a.id,stage:2,choice:"celebrate"});expect(s.journey.badges).toBe(1);expect(()=>chooseCompanyStory(s,{id:a.id,stage:2,choice:"celebrate"})).toThrow();expect(s.historyOutbox.some(x=>x.data.type==="company_story")).toBe(true);});
it("does not count other or late deliveries for a personal story",()=>{const s=storySetup(),a=s.journey.arcs[0];chooseCompanyStory(s,{id:a.id,stage:0,choice:"quality"});for(let n=0;n<5;n++)recordJourneyEvent(s,{type:"delivery_completed",gameTime:s.gameTime,driverId:a.driverId,details:{onTime:false}});expect(a.deliveries).toBe(0);for(let n=0;n<5;n++)recordJourneyEvent(s,{type:"delivery_completed",gameTime:s.gameTime,driverId:a.driverId,details:{onTime:true}});expect(a.stage).toBe(2);});
it("ends gracefully when the story person leaves and preserves identity",()=>{const s=storySetup(),a=s.journey.arcs[0];s.drivers[0].employmentStatus="terminated";processCompanyStories(s,s.gameTime);expect(a.status).toBe("departed");expect(a.name).toBe(s.drivers[0].name);expect(()=>chooseCompanyStory(s,{id:a.id,stage:0,choice:"quality"})).toThrow();});
it("survives save/load without replaying an episode or reward",()=>{const s=storySetup(),a=s.journey.arcs[0];chooseCompanyStory(s,{id:a.id,stage:0,choice:"close"});const loaded=JSON.parse(JSON.stringify(s));processCompanyStories(loaded,loaded.gameTime);expect(loaded.journey).toEqual(s.journey);});
