import React, { useMemo, useState } from "react";
import { Globe2, ShieldCheck, ArrowRight, FileText, Truck } from "lucide-react";
import { useGame } from "@/lib/gameContext";
import { formatEuro, formatGameTime } from "@/lib/gameData";
import { CITIES, COUNTRY_NAMES, countryOf, dachRoute } from "@/lib/simulation/dachGeography";
import { DACH_SOURCES, DACH_RULE_VERSION, regulatoryDate } from "@/lib/simulation/dachRules";
import { buildDeployment } from "@/lib/simulation/tourEngine";
import { vehicleDisplayName } from "@/lib/displayHelpers";

export default function DachPanel(){
 const {state,send,showToast}=useGame();
 const [busy,setBusy]=useState(false),[from,setFrom]=useState("München"),[to,setTo]=useState("Zürich"),[vehicleId,setVehicleId]=useState("");
 const vehicles=(state.vehicles||[]).filter(v=>!["sold","archived"].includes(v.status));
 const vehicle=vehicles.find(v=>v.id===vehicleId)||vehicles[0];
 const route=useMemo(()=>dachRoute(from,to),[from,to]);
 const plan=useMemo(()=>{
  if(!vehicle||!state.dach?.enabled)return null;
  return buildDeployment(state,{id:"preview",fromCity:from,toCity:to,paymentCents:0,deliveryDeadlineMin:state.gameTime+14*1440,transportRulesVersion:DACH_RULE_VERSION},vehicle,from,state.gameTime,{workMin:0,driveMin:0});
 },[vehicle,from,to,state]);
 async function act(command,params={}){
  setBusy(true);try{await send(command,params);showToast(command==="activateDach"?"DACH-Betrieb aktiviert. Neue Marktangebote folgen mit der nächsten Welle.":"Lkw dem lokalen Betrieb zugeordnet.","success");}
  catch(e){showToast(e.message,"error");}finally{setBusy(false);}
 }
 const input="w-full bg-slate-950 text-slate-100 border border-white/20 rounded-xl p-3";
 return <div className="space-y-5">
  <section className="rounded-2xl border border-lime/25 bg-slate-950/95 p-5 sm:p-7 space-y-4">
   <div className="flex gap-3 items-start"><Globe2 className="w-8 h-8 text-lime shrink-0"/><div><p className="text-xs tracking-widest text-lime uppercase">Drei Länder. Ein Netzwerk.</p><h2 className="text-2xl font-semibold mt-1">Dein Betrieb in DACH</h2><p className="text-sm text-slate-300 mt-2">73 Logistikstandorte in Deutschland, Österreich und der Schweiz. Ländermaut, Zollagentur, Fahrverbote und Kabotage fließen in die Planung ein.</p></div></div>
   {!state.dach?.enabled?<div className="space-y-3"><p className="text-sm text-slate-300">Aktivierung gilt für neue Marktaufträge und Überstellungen. Bereits zugesagte deutsche Aufträge behalten ihre bisherigen Regeln. Ausländische Filialen repräsentieren im Spiel lizenzierte lokale Betriebe; Gründung, Genehmigungen und Steuerverwaltung werden vereinfacht abgewickelt.</p><button disabled={busy} onClick={()=>act("activateDach")} className="px-5 py-3 rounded-xl bg-lime text-ink font-semibold disabled:opacity-50">{busy?"Wird aktiviert …":"DACH-Betrieb aktivieren"}</button></div>:<div className="flex flex-wrap gap-3 text-sm text-lime"><span className="flex items-center gap-2"><ShieldCheck size={17}/> DACH aktiv</span><span>Regelkalender: {regulatoryDate(state.gameTime).toLocaleDateString("de-DE",{timeZone:"UTC"})}</span><span>{DACH_RULE_VERSION}</span></div>}
  </section>
  <div className="grid md:grid-cols-3 gap-3">{Object.entries(COUNTRY_NAMES).map(([country,name])=><section key={country} className="rounded-2xl bg-slate-950/95 border border-white/10 p-5"><span className="text-lime text-xs tracking-widest">{country}</span><h3 className="text-lg font-semibold mt-1">{name}</h3><p className="text-sm text-slate-300 mt-2">{CITIES.filter(c=>countryOf(c)===country).length} Standorte · {(state.branches||[]).filter(b=>b.status==="active"&&countryOf(b.city)===country).length} eigene Filialen</p><p className="text-xs text-slate-400 mt-3">{country==="DE"?"Kilometermaut · Sonn- und Feiertagsruhe":country==="AT"?"GO-Maut auch für E-Lkw · Nacht- und Wochenendruhe":"LSVA nach Gewicht · Zollabwicklung · Nacht- und Sonntagsruhe"}</p></section>)}</div>
  <section className="rounded-2xl bg-slate-950/95 border border-white/10 p-5 space-y-4">
   <h3 className="font-semibold flex gap-2 items-center"><ArrowRight size={18}/> Routen- und Kostencheck</h3>
   <div className="grid sm:grid-cols-3 gap-3"><label className="text-sm">Abholung<select className={input} value={from} onChange={e=>setFrom(e.target.value)}>{CITIES.map(c=><option key={c}>{c}</option>)}</select></label><label className="text-sm">Ziel<select className={input} value={to} onChange={e=>setTo(e.target.value)}>{CITIES.map(c=><option key={c}>{c}</option>)}</select></label><label className="text-sm">Lkw<select className={input} value={vehicle?.id||""} onChange={e=>setVehicleId(e.target.value)}>{vehicles.map(v=><option key={v.id} value={v.id}>{vehicleDisplayName(v)}</option>)}</select></label></div>
   <p className="text-sm text-slate-300">{route.totalKm} km Modellstrecke {route.crossing&&"· Grenzübergang "+route.crossing.id}</p>
   {plan?.transport&&<><div className="overflow-x-auto"><table className="w-full text-sm text-left"><thead className="text-slate-400"><tr><th className="py-2">Land</th><th>Strecke</th><th>Maut / LSVA</th></tr></thead><tbody>{plan.transport.breakdown.map(x=><tr key={x.country} className="border-t border-white/10"><td className="py-2">{COUNTRY_NAMES[x.country]}</td><td>{x.distanceKm} km</td><td>{formatEuro(x.cents)}</td></tr>)}</tbody></table></div><p className="text-sm">Zollagentur: {formatEuro(plan.customsCents||0)} · Frühestes Ende: {formatGameTime(plan.endMin)}</p>{plan.energyError&&<p role="status" className="text-amber-200 border border-amber-300/20 rounded-xl p-3">{plan.energyError}</p>}<p className="text-xs text-slate-400">Vorschau ab Abholort mit ausgeruhtem Fahrer und aktuellem Akku. Die tatsächliche Disposition berücksichtigt zusätzlich Anfahrt, Fahrerzähler, Termine und Reservierungen.</p></>}
   {!state.dach?.enabled&&<p className="text-sm text-slate-400">Für die vollständige Kosten- und Regelprüfung DACH aktivieren.</p>}
   <div className="rounded-xl bg-white/5 p-4 text-sm text-slate-300"><p className="flex items-center gap-2 font-medium text-slate-100"><FileText size={16}/> Begleitpapiere & Zoll</p><p className="mt-2">{route.crossing?.customs?"Schweizer Grenze: Frachtbrief, Handelsrechnung, Packliste sowie Ausfuhr-/Einfuhrabwicklung über die automatische Zollagentur. Das Spiel rechnet 65 € Service und 90 Minuten je beladener Grenzpassage.":"Im vereinfachten Unionswarenmodell zwischen Deutschland und Österreich fällt keine Zollabfertigung an; grenzüberschreitende Transporte führen einen CMR-Frachtbrief."}</p><p className="mt-2 text-xs text-slate-400">Die Agenturgebühr ist kein Warenzoll. Zolltarifnummer, Ursprung, Warenwert, Einfuhrumsatzsteuer und Sonderwaren sind nicht pauschal berechenbar und werden nicht als Frachtführerkosten erfunden.</p></div>
  </section>
  {state.dach?.enabled&&<section className="rounded-2xl bg-slate-950/95 border border-white/10 p-5 space-y-3"><h3 className="font-semibold flex items-center gap-2"><Truck size={18}/> Lokale Betriebszuordnung</h3><p className="text-sm text-slate-300">Die reine Filialzuweisung ändert nicht die Transportberechtigung. Für Schweizer Binnenaufträge wird ein Schweizer Lkw benötigt. EU-Kabotage ist im Spiel nach beladener Einfahrt auf drei Transporte in sieben Tagen begrenzt; nach Ausfahrt gilt eine viertägige Abkühlfrist.</p>{vehicles.filter(v=>v.operatorCountry&&v.operatorCountry!==countryOf((state.branches||[]).find(b=>b.id===v.branchId)?.city)).map(v=><div key={v.id} className="flex flex-wrap gap-3 items-center justify-between rounded-xl bg-white/5 p-3"><span className="text-sm">{vehicleDisplayName(v)} · Betrieb {v.operatorCountry}</span><button disabled={busy} onClick={()=>act("registerDachVehicle",{vehicleId:v.id})} className="border border-lime/40 rounded-lg px-3 py-2 text-sm text-lime">Lokal registrieren · 800 €</button></div>)}<p className="text-xs text-slate-400">Spielpauschale für freie eigene Lkw an ihrer Heimatfiliale. Reale Einfuhrabgaben, Zulassungsvoraussetzungen und Gesellschaftsgründung sind damit nicht abgebildet.</p></section>}
  <details className="rounded-2xl bg-slate-950/95 border border-white/10 p-5 text-sm"><summary className="cursor-pointer font-semibold">Regelumfang, Modellgrenzen und amtliche Quellen</summary><div className="mt-4 space-y-3 text-slate-300"><p>Stand 22.09.2026, eingefrorene Spielregeln. Tarifprofile: Euro VI / CO₂-Klasse 1 beziehungsweise emissionsfreie Lkw, typisierte Gewichte und Achsen. Schweizer Franken werden mit dem Spielkurs 1 CHF = 1,05 € gerechnet. Mautstrecken sind angenähert; Sondermaut und reale Straßenrestriktionen sind nicht enthalten.</p><p>Der Regelkalender beginnt Montag, 05.01.2026, und läuft gregorianisch; die bestehende 30-Tage-Buchhaltungsperiode bleibt bestehen. Nationale Feiertage werden berücksichtigt. Regionale Feiertage, deutsche Sommerfahrverbote, Tiroler Sonderfahrverbote, Umweltzonen, individuelle Genehmigungen und internationale Gefahrgut-/Tunnelrouten sind noch nicht vollständig abgebildet. Internationales Gefahrgut wird deshalb nicht disponiert.</p><p>Die Fahrerplanung verwendet weiterhin konservative 8 Arbeitsstunden und 12 Stunden Tagesruhe, ergänzt um höchstens 56 Lenkstunden pro Woche, 90 in zwei Wochen und 45 Stunden Wochenruhe nach spätestens sechs Tagen. Ausnahme- und Ausgleichsregelungen werden nicht ausgenutzt.</p><p>CMR-Haftung, Entsendung/Mindestlohn, Umsatzsteuer, Zollverfahren und lokale Betriebslizenzen werden organisatorisch vorausgesetzt; dies ist keine vollständige rechtliche Transportsimulation. Alle neuen Einschränkungen und Kosten stehen in der Transportvorschau.</p><div className="grid sm:grid-cols-2 gap-2">{DACH_SOURCES.map(s=><a key={s.url} href={s.url} target="_blank" rel="noreferrer" className="text-lime underline underline-offset-4">{s.label}</a>)}</div></div></details>
 </div>;
}
